/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BangXepHangRouteImport } from './routes/bang-xep-hang'
import { Route as HuongDanRouteImport } from './routes/huong-dan'
import { Route as LichSuRouteImport } from './routes/lich-su'
import { Route as NhanVatRouteImport } from './routes/nhan-vat'
import { Route as ThiRouteImport } from './routes/thi'
import { Route as AuthenticatedNhapDuLieuRouteImport } from './routes/_authenticated/nhap-du-lieu'
import { Route as AuthenticatedNhatKyRouteImport } from './routes/_authenticated/nhat-ky'
import { Route as AuthenticatedQuanTriRouteImport } from './routes/_authenticated/quan-tri'
import { Route as CuocThiQuizIdRouteImport } from './routes/cuoc-thi.$quizId'
import { Route as ApiPublicExamProgressRouteImport } from './routes/api/public/exam-progress'
import { Route as ApiPublicAnhBiaSplatRouteImport } from './routes/api/public/anh-bia.$'
import { Route as ApiPublicAnhCauHoiSplatRouteImport } from './routes/api/public/anh-cau-hoi.$'
import { Route as ApiPublicCronAutoSubmitRouteImport } from './routes/api/public/cron/auto-submit'
import { Route as ApiPublicCronDonAnhRouteImport } from './routes/api/public/cron/don-anh'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BangXepHangRoute = BangXepHangRouteImport.update({
  id: '/bang-xep-hang',
  path: '/bang-xep-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const HuongDanRoute = HuongDanRouteImport.update({
  id: '/huong-dan',
  path: '/huong-dan',
  getParentRoute: () => rootRouteImport,
} as any)
const LichSuRoute = LichSuRouteImport.update({
  id: '/lich-su',
  path: '/lich-su',
  getParentRoute: () => rootRouteImport,
} as any)
const NhanVatRoute = NhanVatRouteImport.update({
  id: '/nhan-vat',
  path: '/nhan-vat',
  getParentRoute: () => rootRouteImport,
} as any)
const ThiRoute = ThiRouteImport.update({
  id: '/thi',
  path: '/thi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNhapDuLieuRoute = AuthenticatedNhapDuLieuRouteImport.update({
  id: '/nhap-du-lieu',
  path: '/nhap-du-lieu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNhatKyRoute = AuthenticatedNhatKyRouteImport.update({
  id: '/nhat-ky',
  path: '/nhat-ky',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuanTriRoute = AuthenticatedQuanTriRouteImport.update({
  id: '/quan-tri',
  path: '/quan-tri',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CuocThiQuizIdRoute = CuocThiQuizIdRouteImport.update({
  id: '/cuoc-thi/$quizId',
  path: '/cuoc-thi/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExamProgressRoute = ApiPublicExamProgressRouteImport.update({
  id: '/api/public/exam-progress',
  path: '/api/public/exam-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnhBiaSplatRoute = ApiPublicAnhBiaSplatRouteImport.update({
  id: '/api/public/anh-bia/$',
  path: '/api/public/anh-bia/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnhCauHoiSplatRoute = ApiPublicAnhCauHoiSplatRouteImport.update({
  id: '/api/public/anh-cau-hoi/$',
  path: '/api/public/anh-cau-hoi/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronAutoSubmitRoute = ApiPublicCronAutoSubmitRouteImport.update({
  id: '/api/public/cron/auto-submit',
  path: '/api/public/cron/auto-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDonAnhRoute = ApiPublicCronDonAnhRouteImport.update({
  id: '/api/public/cron/don-anh',
  path: '/api/public/cron/don-anh',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bang-xep-hang': typeof BangXepHangRoute
  '/huong-dan': typeof HuongDanRoute
  '/lich-su': typeof LichSuRoute
  '/nhan-vat': typeof NhanVatRoute
  '/thi': typeof ThiRoute
  '/nhap-du-lieu': typeof AuthenticatedNhapDuLieuRoute
  '/nhat-ky': typeof AuthenticatedNhatKyRoute
  '/quan-tri': typeof AuthenticatedQuanTriRoute
  '/cuoc-thi/$quizId': typeof CuocThiQuizIdRoute
  '/api/public/exam-progress': typeof ApiPublicExamProgressRoute
  '/api/public/anh-bia/$': typeof ApiPublicAnhBiaSplatRoute
  '/api/public/anh-cau-hoi/$': typeof ApiPublicAnhCauHoiSplatRoute
  '/api/public/cron/auto-submit': typeof ApiPublicCronAutoSubmitRoute
  '/api/public/cron/don-anh': typeof ApiPublicCronDonAnhRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bang-xep-hang': typeof BangXepHangRoute
  '/huong-dan': typeof HuongDanRoute
  '/lich-su': typeof LichSuRoute
  '/nhan-vat': typeof NhanVatRoute
  '/thi': typeof ThiRoute
  '/nhap-du-lieu': typeof AuthenticatedNhapDuLieuRoute
  '/nhat-ky': typeof AuthenticatedNhatKyRoute
  '/quan-tri': typeof AuthenticatedQuanTriRoute
  '/cuoc-thi/$quizId': typeof CuocThiQuizIdRoute
  '/api/public/exam-progress': typeof ApiPublicExamProgressRoute
  '/api/public/anh-bia/$': typeof ApiPublicAnhBiaSplatRoute
  '/api/public/anh-cau-hoi/$': typeof ApiPublicAnhCauHoiSplatRoute
  '/api/public/cron/auto-submit': typeof ApiPublicCronAutoSubmitRoute
  '/api/public/cron/don-anh': typeof ApiPublicCronDonAnhRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bang-xep-hang': typeof BangXepHangRoute
  '/huong-dan': typeof HuongDanRoute
  '/lich-su': typeof LichSuRoute
  '/nhan-vat': typeof NhanVatRoute
  '/thi': typeof ThiRoute
  '/_authenticated/nhap-du-lieu': typeof AuthenticatedNhapDuLieuRoute
  '/_authenticated/nhat-ky': typeof AuthenticatedNhatKyRoute
  '/_authenticated/quan-tri': typeof AuthenticatedQuanTriRoute
  '/cuoc-thi/$quizId': typeof CuocThiQuizIdRoute
  '/api/public/exam-progress': typeof ApiPublicExamProgressRoute
  '/api/public/anh-bia/$': typeof ApiPublicAnhBiaSplatRoute
  '/api/public/anh-cau-hoi/$': typeof ApiPublicAnhCauHoiSplatRoute
  '/api/public/cron/auto-submit': typeof ApiPublicCronAutoSubmitRoute
  '/api/public/cron/don-anh': typeof ApiPublicCronDonAnhRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bang-xep-hang'
    | '/huong-dan'
    | '/lich-su'
    | '/nhan-vat'
    | '/thi'
    | '/nhap-du-lieu'
    | '/nhat-ky'
    | '/quan-tri'
    | '/cuoc-thi/$quizId'
    | '/api/public/exam-progress'
    | '/api/public/anh-bia/$'
    | '/api/public/anh-cau-hoi/$'
    | '/api/public/cron/auto-submit'
    | '/api/public/cron/don-anh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bang-xep-hang'
    | '/huong-dan'
    | '/lich-su'
    | '/nhan-vat'
    | '/thi'
    | '/nhap-du-lieu'
    | '/nhat-ky'
    | '/quan-tri'
    | '/cuoc-thi/$quizId'
    | '/api/public/exam-progress'
    | '/api/public/anh-bia/$'
    | '/api/public/anh-cau-hoi/$'
    | '/api/public/cron/auto-submit'
    | '/api/public/cron/don-anh'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bang-xep-hang'
    | '/huong-dan'
    | '/lich-su'
    | '/nhan-vat'
    | '/thi'
    | '/_authenticated/nhap-du-lieu'
    | '/_authenticated/nhat-ky'
    | '/_authenticated/quan-tri'
    | '/cuoc-thi/$quizId'
    | '/api/public/exam-progress'
    | '/api/public/anh-bia/$'
    | '/api/public/anh-cau-hoi/$'
    | '/api/public/cron/auto-submit'
    | '/api/public/cron/don-anh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BangXepHangRoute: typeof BangXepHangRoute
  HuongDanRoute: typeof HuongDanRoute
  LichSuRoute: typeof LichSuRoute
  NhanVatRoute: typeof NhanVatRoute
  ThiRoute: typeof ThiRoute
  CuocThiQuizIdRoute: typeof CuocThiQuizIdRoute
  ApiPublicExamProgressRoute: typeof ApiPublicExamProgressRoute
  ApiPublicAnhBiaSplatRoute: typeof ApiPublicAnhBiaSplatRoute
  ApiPublicAnhCauHoiSplatRoute: typeof ApiPublicAnhCauHoiSplatRoute
  ApiPublicCronAutoSubmitRoute: typeof ApiPublicCronAutoSubmitRoute
  ApiPublicCronDonAnhRoute: typeof ApiPublicCronDonAnhRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bang-xep-hang': {
      id: '/bang-xep-hang'
      path: '/bang-xep-hang'
      fullPath: '/bang-xep-hang'
      preLoaderRoute: typeof BangXepHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huong-dan': {
      id: '/huong-dan'
      path: '/huong-dan'
      fullPath: '/huong-dan'
      preLoaderRoute: typeof HuongDanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lich-su': {
      id: '/lich-su'
      path: '/lich-su'
      fullPath: '/lich-su'
      preLoaderRoute: typeof LichSuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nhan-vat': {
      id: '/nhan-vat'
      path: '/nhan-vat'
      fullPath: '/nhan-vat'
      preLoaderRoute: typeof NhanVatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thi': {
      id: '/thi'
      path: '/thi'
      fullPath: '/thi'
      preLoaderRoute: typeof ThiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nhap-du-lieu': {
      id: '/_authenticated/nhap-du-lieu'
      path: '/nhap-du-lieu'
      fullPath: '/nhap-du-lieu'
      preLoaderRoute: typeof AuthenticatedNhapDuLieuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nhat-ky': {
      id: '/_authenticated/nhat-ky'
      path: '/nhat-ky'
      fullPath: '/nhat-ky'
      preLoaderRoute: typeof AuthenticatedNhatKyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quan-tri': {
      id: '/_authenticated/quan-tri'
      path: '/quan-tri'
      fullPath: '/quan-tri'
      preLoaderRoute: typeof AuthenticatedQuanTriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/cuoc-thi/$quizId': {
      id: '/cuoc-thi/$quizId'
      path: '/cuoc-thi/$quizId'
      fullPath: '/cuoc-thi/$quizId'
      preLoaderRoute: typeof CuocThiQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/exam-progress': {
      id: '/api/public/exam-progress'
      path: '/api/public/exam-progress'
      fullPath: '/api/public/exam-progress'
      preLoaderRoute: typeof ApiPublicExamProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/anh-bia/$': {
      id: '/api/public/anh-bia/$'
      path: '/api/public/anh-bia/$'
      fullPath: '/api/public/anh-bia/$'
      preLoaderRoute: typeof ApiPublicAnhBiaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/anh-cau-hoi/$': {
      id: '/api/public/anh-cau-hoi/$'
      path: '/api/public/anh-cau-hoi/$'
      fullPath: '/api/public/anh-cau-hoi/$'
      preLoaderRoute: typeof ApiPublicAnhCauHoiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/auto-submit': {
      id: '/api/public/cron/auto-submit'
      path: '/api/public/cron/auto-submit'
      fullPath: '/api/public/cron/auto-submit'
      preLoaderRoute: typeof ApiPublicCronAutoSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/don-anh': {
      id: '/api/public/cron/don-anh'
      path: '/api/public/cron/don-anh'
      fullPath: '/api/public/cron/don-anh'
      preLoaderRoute: typeof ApiPublicCronDonAnhRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedNhapDuLieuRoute: typeof AuthenticatedNhapDuLieuRoute
  AuthenticatedNhatKyRoute: typeof AuthenticatedNhatKyRoute
  AuthenticatedQuanTriRoute: typeof AuthenticatedQuanTriRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedNhapDuLieuRoute: AuthenticatedNhapDuLieuRoute,
  AuthenticatedNhatKyRoute: AuthenticatedNhatKyRoute,
  AuthenticatedQuanTriRoute: AuthenticatedQuanTriRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BangXepHangRoute: BangXepHangRoute,
  HuongDanRoute: HuongDanRoute,
  LichSuRoute: LichSuRoute,
  NhanVatRoute: NhanVatRoute,
  ThiRoute: ThiRoute,
  CuocThiQuizIdRoute: CuocThiQuizIdRoute,
  ApiPublicExamProgressRoute: ApiPublicExamProgressRoute,
  ApiPublicAnhBiaSplatRoute: ApiPublicAnhBiaSplatRoute,
  ApiPublicAnhCauHoiSplatRoute: ApiPublicAnhCauHoiSplatRoute,
  ApiPublicCronAutoSubmitRoute: ApiPublicCronAutoSubmitRoute,
  ApiPublicCronDonAnhRoute: ApiPublicCronDonAnhRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
